### ISSUE TITLE
KeyError: 'session'

### ISSUE THREAD

**Issue by Ge0** [mrasband/aiohttp-oauth2#5]
Hey there,

When I try to use oauth2 with google, once I select my Google account, I am being redirected on my website and I get an error 500 with this traceback:

```
Traceback (most recent call last):
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
    return await handler(request)
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp_babel\middlewares.py", line 25, in babel_middleware
    return await handler(request)
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp_session\__init__.py", line 154, in factory
    response = await handler(request)
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
    return await handler(request)
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp\web_urldispatcher.py", line 892, in _iter
    resp = await method()
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp_oauth2\client\views.py", line 58, in get
    async with self.request.app["session"].post(
  File "c:\users\geoffrey\envs\lampee\lib\site-packages\aiohttp\web_app.py", line 160, in __getitem__
    return self._state[key]
KeyError: 'session'
```

I am no sure of the nature of `app` and I normally have configured sessions on my side.

```python
def load_web_app():
    app = web.Application(middlewares=[babel_middleware])
    fernet_key = fernet.Fernet.generate_key()
    secret_key = base64.urlsafe_b64decode(fernet_key)
    setup(app, EncryptedCookieStorage(secret_key))
    app.add_subapp(
        "/google/",  # any arbitrary prefix
        oauth2_app(
            client_id=os.getenv("GOOGLE_CLIENT_ID"),
            client_secret=os.getenv("GOOGLE_SECRET_ID"),
            authorize_url="https://accounts.google.com/o/oauth2/v2/auth",
            token_url="https://www.googleapis.com/oauth2/v4/token",
            scopes=["https://www.googleapis.com/auth/userinfo.email"],
            # add scopes if you want to customize them
            # optionally add an on_login coroutine to handle the post-login
            # logic
            # it should expect the request and the oauth2 access code response
            on_login=on_oauth2_login,
        ),
    )

    jinja2_env = aiohttp_jinja2.setup(
        app, loader=jinja2.FileSystemLoader(f"{settings.BASE_DIR}/templates")
    )
    app.add_routes(routes)
    app.router.add_static("/static/", f"{settings.BASE_DIR}/static")
    app["static_root_url"] = "/static/"
    jinja2_env.globals["_"] = _
    return app
```

Am I missing something?

**Comment by mattrasband** [comment]
Sorry I missed this, I will take a look and get back to you @Ge0 !

**Comment by mattrasband** [comment]
What's in your `on_oauth2_login`? It may be an oddity that the `request` and `request.app` given there are for the google oauth2 application and not your main web application. You could probably work around that by using a partial for `on_oauth2_login` or using `request.config_dict` which should resolve keys from parent apps.

**Comment by mattrasband** [comment]
Feel free to  reopen this if you need, but my guess is my turnaround was a little too long.

**Comment by Ge0** [comment]
Hey @mrasband sorry for the delay.

I have found a workaround anyway so I’d reopen if I face such a case once again.

Thank you!

**Comment by mattrasband** [comment]
No worries at all, I am trying to be better about checking notifications for these, I wasn't sure how used it was :)
